### ISSUE TITLE
Add an output so that later action jobs can check if this action has acquired a lock

### ISSUE THREAD

**Issue by benmccown** [suzuki-shunsuke/lock-action#131]
### version

`suzuki-shunsuke/lock-action@c752be910ac812e0adc50316855416514d364b57`

(should be v0.1.3)

### Overview

I'm testing your action for use in my team's release pipeline. Recently the GitHub API call for creating the lock returned an unknown error (see the "actual behavior" section for the log message) but the lock was still created. This is problematic since the rest of the GitHub Workflow then failed due to the failed job, but the deployment lock exists and is blocking deployments. A successful deployment is required before the lock will be released, meaning we need to manually unlock the pipeline to get things back to a working state.

Worthy of note is that I'm running this lock action from self hosted CI runners that we own/maintain in AWS. Maybe this was just a transient network issue, but I'm opening the ticket in case there's a way to handle this error more gracefully or possibly add some smarter retry logic to the GitHub API request. Maybe if a `502` is received when creating a lock, a subsequent API call could be made to check for the existence of the lock in case it was created successfully. Or maybe it could blindly retry creating the lock (via the GitHub API call) and gracefully handle the "lock already exists" error.

### How to reproduce

GitHub Actions Workflow

```yaml
      - name: Acquire Deployment Lock
        uses: suzuki-shunsuke/lock-action@c752be910ac812e0adc50316855416514d364b57 # v0.1.3
        with:
          mode: lock
          key: dev
          max_wait_seconds: "43200" # 12 hours
          wait_interval_seconds: "10"
```

### Expected behaviour

Lock is created and the GitHub Workflow Job succeeds.

### Actual behaviour

Lock is created, but the GitHub Workflow Job failed. Log message and stack trace shown below.

```
Error: failed to get a key dev: Unknown error: {"data":null,"errors":[{"message":"Something went wrong while executing your query. This may be the result of a timeout, or it could be a GitHub bug. Please include `D28E:3D83BC:26FCC07:27992F6:674E1EC4` when reporting this issue."}]}

/__w/_actions/suzuki-shunsuke/lock-action/c752be910ac812e0adc50316855416514d364b57/dist/index.js:7044
      const error = new import_request_error.RequestError(toErrorMessage(data), status, {
                    ^

RequestError [HttpError]: Unknown error: {"data":null,"errors":[{"message":"Something went wrong while executing your query. This may be the result of a timeout, or it could be a GitHub bug. Please include `D28E:3D83BC:26FCC07:27992F6:674E1EC4` when reporting this issue."}]}
    at /__w/_actions/suzuki-shunsuke/lock-action/c752be910ac812e0adc50316855416514d364b57/dist/index.js:7044:21
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 502,
  response: {
    url: 'https://api.github.com/graphql',
    status: 502,
    headers: {
      'access-control-allow-origin': '*',
      'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset',
      'content-type': 'application/json',
      date: 'Mon, 02 Dec 2024 20:55:32 GMT',
      server: 'github.com',
      'transfer-encoding': 'chunked',
      vary: 'Accept-Encoding, Accept, X-Requested-With',
      'x-github-request-id': 'D28E:3D83BC:26FCC07:27992F6:674E1EC4'
    },
    data: {
      data: null,
      errors: [
        {
          message: 'Something went wrong while executing your query. This may be the result of a timeout, or it could be a GitHub bug. Please include `D28E:3D83BC:26FCC07:27992F6:674E1EC4` when reporting this issue.'
        }
      ]
    }
  },
  request: {
    method: 'POST',
    url: 'https://api.github.com/graphql',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'octokit-core.js/5.2.0 Node.js/20.18.0 (linux; x64)',
      authorization: 'token [REDACTED]',
      'content-type': 'application/json; charset=utf-8'
    },
    body: '{"query":"query($owner: String!, $repo: String!, $ref: String!) {\\n  repository(owner: $owner, name: $repo) {\\n    ref(qualifiedName: $ref) {\\n      prefix\\n      name\\n      target {\\n        ... on Commit {\\n          oid\\n          message\\n          committedDate\\n          tree {\\n            oid\\n          }\\n        } \\n      }\\n    }\\n  }\\n}","variables":{"owner":"Gretellabs","repo":"monogretel","ref":"lock__dev"}}',
    request: {
      agent: Agent {
        _events: [Object: null prototype] {
          free: [Function (anonymous)],
          newListener: [Function: maybeEnableKeylog]
        },
        _eventsCount: 2,
        _maxListeners: undefined,
        defaultPort: 443,
        protocol: 'https:',
        options: [Object: null prototype] {
          keepAlive: false,
          maxSockets: 100,
          noDelay: true,
          path: null
        },
        requests: [Object: null prototype] {},
        sockets: [Object: null prototype] {},
        freeSockets: [Object: null prototype] {},
        keepAliveMsecs: 1000,
        keepAlive: false,
        maxSockets: 100,
        maxFreeSockets: 256,
        scheduling: 'lifo',
        maxTotalSockets: Infinity,
        totalSocketCount: 0,
        maxCachedSessions: 100,
        _sessionCache: { map: {}, list: [] },
        [Symbol(shapeMode)]: false,
        [Symbol(kCapture)]: false
      },
      fetch: [Function: proxyFetch],
      hook: [Function: bound bound register]
    }
  }
}

Node.js v20.18.0
```

**Comment by suzuki-shunsuke** [comment]
Thank you for reporting this issue.

```
Error: failed to get a key dev: Unknown error: {"data":null,"errors":[{"message":"Something went wrong while executing your query. This may be the result of a timeout, or it could be a GitHub bug. Please include `D28E:3D83BC:26FCC07:27992F6:674E1EC4` when reporting this issue."}]}
```

https://github.com/suzuki-shunsuke/lock-action/blob/6a406056d10d6f28b51d8972e109b1ada6d063d4/src/lock.ts#L74

This error occurs when it fails to get a branch by GitHub GraphQL API before acquiring a lock.
This isn't an error when it fails to create or update a branch.

Maybe this action should catch any error and retry the process.

**Comment by benmccown** [comment]
I'm a bit confused. Since this error is thrown, I would expect that the actual lock creation happens in a subsequent step, and that the "create lock" logic wouldn't execute.

However, the lock commit was indeed created on my branch and has its commit message pointing to this job which failed. If the GraphQL error response caused the job to fail, is it correct behavior that the code to create the lock still executed?

I think backoff/retry logic would make sense for this API request if it's just a `GET` operation, but my larger concern is that the GraphQL failure still resulted in the lock being created.

**Comment by suzuki-shunsuke** [comment]
In my understanding, this action fails immediately without retrying when it fails to get a branch due to unknown error.
So this situation looks weird. 🤔

> However, the lock commit was indeed created on my branch and has its commit message pointing to this job which failed.

Did your workflow output the log `The key dev has already been locked. Waiting...`?

**Comment by suzuki-shunsuke** [comment]
> This is problematic since the rest of the GitHub Workflow then failed due to the failed job, but the deployment lock exists and is blocking deployments.
> A successful deployment is required before the lock will be released, meaning we need to manually unlock the pipeline to get things back to a working state.

BTW, you can release the lock even if the action fails by `post_unlock: true`.

https://github.com/suzuki-shunsuke/lock-action?tab=readme-ov-file#how-to-use

**Comment by benmccown** [comment]
@suzuki-shunsuke I apologize, yesterday was my first day back from some time off and I don't think my brain has shifted back into software engineer mode yet :).

The action that failed was actually a `check` action. I see what happened now. My `lock` succeeded but the subsequent `check` failed. See the screen snip below for my pipeline configuration.

![image](https://github.com/user-attachments/assets/2e4d5d5e-7766-4225-9b13-9ed8ce67611c)

The reason I have `check` running after `lock` is that the `lock` action doesn't actually write any github outputs as to whether the lock was successfully acquired. So I leverage the `check` action since it does have some outputs.

The logic looks like this:

1. GitHub Job - Acquire `dev` lock (also runs `check`)
2. GitHub Job - Deploy to `dev`
3. GitHub Job - Run `dev` validation tests after deployment, to ensure a healthy environment
4. GitHub Job - Unlock `dev`. Only runs if `needs.dev-lock.outputs.locked == 'true'` which is output by the `check` action.

The reason I can't use `post_unlock` is that I have separate GitHub Jobs running in between the lock/unlock actions.

So ultimately relating to my bug ticket, I think some backoff/retry for the `check` logic would be good.

Aside from that, if I could relay a feature request as part of our discussion, it would be to have the `lock` behavior output the `locked` boolean the same way the `check` behavior does, so that I don't need to use a redundant `check` step to output whether lock acquisition succeeded or failed. Ultimately I use this boolean later in my GH Workflow to decide whether the `unlock` action should run.

Thanks for your help! I really like the action and that it doesn't have any dependencies and is very lightweight.

**Comment by benmccown** [comment]
@suzuki-shunsuke If you're open to contributions, I've read `CONTRIBUTIONS.md` and could take a crack at adding the `outputs` logic.

**Comment by suzuki-shunsuke** [comment]
Thank you for your explanation.

> The action that failed was actually a check action.

Oh, I see.

> The reason I have check running after lock is that the lock action doesn't actually write any github outputs as to whether the lock was successfully acquired.

> Aside from that, if I could relay a feature request as part of our discussion, it would be to have the lock behavior output the locked boolean the same way the check behavior does, so that I don't need to use a redundant check step to output whether lock acquisition succeeded or failed.

By default, the action with `mode: lock` (I call this `lock mode` here) fails if it can't acquire lock, so I don't think you need to check if the lock is acquired after running lock mode.
That's why lock mode doesn't output `locked`.

> The reason I can't use post_unlock is that I have separate GitHub Jobs running in between the lock/unlock actions.

I see. That sounds reasonable.

> So ultimately relating to my bug ticket, I think some backoff/retry for the check logic would be good.

`max_wait_seconds` and `wait_interval_seconds` should work for `mode: check` too.

**Comment by suzuki-shunsuke** [comment]
> max_wait_seconds and wait_interval_seconds should work for mode: check too.

This is correct, but when GitHub API returns 502 error, the retry doesn't work now.

https://github.com/suzuki-shunsuke/lock-action/blob/549b6aaba56ba3ac20dc4a1d985cda88ba0c7a36/src/check.ts#L113-L116

**Comment by benmccown** [comment]
@suzuki-shunsuke 

> By default, the action with mode: lock (I call this lock mode here) fails if it can't acquire lock, so I don't think you need to check if the lock is acquired after running lock mode.
> That's why lock mode doesn't output locked.

Let me preface my comment by saying I know this item of discussion isn't directly related to this present 502 issue, so if you'd like me to cut a feature request issue I can!

The reason I need a GitHub output is that I conditionally want to unlock in a later GitHub Job within the same workflow. If someone cancels the GitHub Workflow while it's in flight, or if there is an error somewhere in the workflow, I only want to release the lock if that workflow execution was the one who acquired that lock.

Again, to do this my condition for the `lock-cleanup` job looks like:

```
    if: |
      always() && 
      needs.dev-lock.outputs.locked == 'true'
```

The reason I need an output is because I'm using separate GitHub Jobs within the same Workflow, so `post_unlock` doesn't work for me.

If my `lock` action fails or if it never ran successfully in the first place (due to someone cancelling the workflow run) I don't want to release the lock. This is because my pipeline supports parallel executions and there could be another parallel workflow run that has already acquired the lock and is doing something, during the time it took for my workflow run to go from the `lock` job to the `unlock` job.

Hope that makes sense.

---

> This is correct, but when GitHub API returns 502 error, the retry doesn't work now.

If I'm understanding correctly, you're saying we'd need to handle the 502 more gracefully in that catch block _only_ when `max_wait_seconds` or `wait_interval_seconds` are set so that the implicit "retry" logic we get from the interval based polling will take effect?

**Comment by suzuki-shunsuke** [comment]
Oh, I see. Thank you for your explanation.
The workaround is to add a step for the output `locked`.

```yaml
      - name: Acquire Deployment Lock
        uses: suzuki-shunsuke/lock-action@c752be910ac812e0adc50316855416514d364b57 # v0.1.3
        with:
          mode: lock
          key: dev
          max_wait_seconds: "43200" # 12 hours
          wait_interval_seconds: "10"
      - id: locked
        run: echo "value=true" >> "$GITHUB_OUTPUT"
```

If the lock is acquired, the output is `true`, otherwise the output isn't set.
But if the action outputs `locked`, we don't need to add such a step and the code becomes simpler.

> If I'm understanding correctly, you're saying we'd need to handle the 502 more gracefully in that catch block only when max_wait_seconds or wait_interval_seconds are set so that the implicit "retry" logic we get from the interval based polling will take effect?

Yes, the action should retry until `max_wait_seconds`.
If it isn't set, the action should exit soon.

**Comment by benmccown** [comment]
Ah, that makes a lot of sense. Thanks for your help!

**Comment by suzuki-shunsuke** [comment]
- https://github.com/suzuki-shunsuke/lock-action/pull/135

**Comment by suzuki-shunsuke** [comment]
Could you try [v0.1.4-5](https://github.com/suzuki-shunsuke/lock-action/releases/tag/v0.1.4-5)?
I've added an output `locked`. #135

**Comment by suzuki-shunsuke** [comment]
- https://github.com/suzuki-shunsuke/lock-action/issues/143
